# Generated by Django 4.2.6 on 2023-11-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_askhr_id_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='d9ca7218-0a0c-4ed1-9e31-c2f1ce0caf31', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='2ff945db-3cc3-44a1-a850-63308f0afc7d', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='0b0aa331-550d-47c7-a3d9-ff9b61783f59', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='4ab8fc04-508e-4cdf-88dd-33615fdca3d7', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.CharField(default='65127127-98c0-4a05-b67a-05ccf4b208f0', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='a36d714a-8536-4047-9ce1-bc1f9c60f6bd', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
