# Generated by Django 4.2.6 on 2023-11-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_askhr_id_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='78bc2d79-572e-47e8-992f-b891f868f587', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='b1f8c72c-ccdd-4081-b3a9-b8aecd673f30', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='cbe9a2c7-5e09-41fd-9569-0244b8eb2699', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='dc22791a-00d0-47cb-b734-9a61b7c56395', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.CharField(default='76c8a027-9940-49aa-88ed-9174cb05342f', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='7eb5d155-9534-4e9c-8077-c7ff14d1d3d9', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
