# Generated by Django 4.2.6 on 2023-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_askhr_id_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='req_from',
            field=models.CharField(default='Ujjwal Jamuar', max_length=300),
        ),
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='4dc28ede-d38d-469e-bc89-68fbb7734ad6', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='askhr',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='71157711-b1c0-488d-b0bd-e4d72e82b93e', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='2bc6a02a-4c5e-4989-8dd7-0a30e6ab90d0', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fed_body',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='9933cb9a-b84b-4768-96fd-5064d399708d', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.CharField(default='ad2cf553-2735-4780-b51f-8b590e5a4925', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='type',
            field=models.CharField(default='Casual', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='85e08e00-4e1c-4ec7-b8f3-6e8432675d00', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
