# Generated by Django 4.2.6 on 2023-11-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_leaverequest_type_alter_askhr_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='askhr',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='6c713125-b4c9-4247-9e93-ac2956c20eab', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='f5a53e6c-d4f7-420b-97d7-109b3e05d41d', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='3c69219f-00e5-4474-ba3e-540a29947620', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='398269c5-851f-4c5f-ba20-d74280b0c372', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='38b3c0b2-b722-4720-88b6-ecf1695e295c', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
