# Generated by Django 4.2.6 on 2023-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_askhr_date_feedback_date_alter_askhr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='7e1a72cf-76b0-4361-8554-d96f14729cfb', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='ba227301-a80f-4874-a0b9-36e9a699021a', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='349abee5-b5b9-46a4-8749-b16481c9e521', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='a2baa655-52a8-49f1-861c-dc38f08122ae', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='ec3c19af-092e-409a-9316-aa20e761d992', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
