# Generated by Django 4.2.6 on 2023-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_askhr_id_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='da083515-51ca-4127-8900-ccb644220fdb', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='90048a69-0175-461f-ba54-474e6ed1d588', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='0ae07912-1f3c-47ca-b4c2-cbfd48a20e07', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='f4e06bcc-7f72-4a22-b661-71c7bbb53796', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='551eda6e-4057-4602-9292-9e5a29bb8ae3', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
