# Generated by Django 4.2.6 on 2023-11-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_askhr_id_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='94c25634-473a-4eb8-88c2-5eac41ee7c32', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='8274fd6d-f56b-4a6e-8ae7-e0cd99a86c3d', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='f6e74914-2ad9-4723-85ed-0b5976a0289d', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='951e36c8-3534-46d7-952c-df6d23ade09c', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='16aea898-1bc1-405e-8fb7-19b90f681924', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
