# Generated by Django 4.2.6 on 2023-11-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_askhr_id_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='cfee5552-3526-4a5a-9171-a65c8f6e37fb', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='5536c84b-7b9f-48be-85d4-8d4152a0f25f', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='4f04ae32-546a-4cdf-a115-3febd9edcf0c', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='508495b7-6c14-4dff-a868-4a120e23b9ac', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='3e135154-3ffa-4569-a48a-4af214ac3f29', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
