# Generated by Django 4.2.6 on 2023-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_askhr_id_alter_department_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askhr',
            name='id',
            field=models.CharField(default='4aafb718-9f91-4b3f-9603-ddace3b4542e', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='26ce7790-7002-464c-b1fe-0ae76b43f66a', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='ffa03bee-d6af-49ca-bdd5-a7d43b2ef52f', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.CharField(default='c15609c5-991c-4c2c-8006-dd452ce154a9', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default='a269c127-443f-48de-9c52-5b141584eff5', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
