# Generated by Django 4.2.6 on 2023-11-04 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default='4097715b-cda4-41e9-ac76-95e16afa9772', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default='96922594-e353-4182-bf52-dab6f44564bc', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('designation', models.CharField(default='Employee', max_length=80)),
                ('sick_leave', models.IntegerField(default=12)),
                ('casual_leave', models.IntegerField(default=5)),
                ('annual_leave', models.IntegerField(default=5)),
                ('phone_number', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('profile_url', models.CharField(blank=True, max_length=30, null=True)),
                ('did', models.ForeignKey(blank=True, default='did_default', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('hr_id', models.ForeignKey(blank=True, default='hr_id_default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to='employee.employee')),
                ('manager_id', models.ForeignKey(blank=True, default='manager_id_default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default='22b0edf3-b983-496a-9f24-eb2abcd24206', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.CharField(default='8bcde8f8-5724-487b-bfb9-f19f09ee0a12', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('type', models.CharField(default='Casual', max_length=30)),
                ('req_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'LeaveRequest',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(default='22bed5e9-78d3-4e0f-97b6-e0cd99fa90b8', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('fed_body', models.CharField(max_length=50)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('fed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='employee.employee')),
                ('fed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_feedback', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='pid',
            field=models.ForeignKey(blank=True, default='pid_default', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project'),
        ),
        migrations.CreateModel(
            name='askHR',
            fields=[
                ('id', models.CharField(default='8643bad6-9f95-4945-b7b7-fa816c3d636c', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('hr_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'AskHR',
            },
        ),
    ]
